ansible_become: true
admin_user: devops
node_exporter_version: 1.8.2
promtail_version: 3.3.2
minio_bucket: tfstate
app_domain: exam-devops.duckdns.org
acme_email: you@example.com
ssh_public_key_path: /mnt/c/Users/sergi/.ssh/id_ed25519.pub
ssh_disable_password_auth: false
enable_tailscale: false
enable_jenkins_agent: false
enable_monitoring_stack: true
jenkins_docker_image: jenkins/jenkins:2.568.1-jdk21
